source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods, since Xcode is beta
inhibit_all_warnings!

def test_pods
  inherit! :search_paths
  pod 'Quick',  '~> 2.0.0'
  pod 'Nimble', '~> 8.0.1'
end


target 'LemiTravel' do
  
  pod 'IQKeyboardManagerSwift',     '~> 6.2.1'              # Codeless Keyboard Manager
  pod 'Kingfisher',                 '~> 5.3.1'              # Loading of url image into imageViews
  pod 'Localize-Swift',             '~> 2.0.0'              # Localization
  pod 'Moya',                       '~> 13.0.0'             # Networking Abstraction Layer
  pod 'SnapKit',                    '~> 4.2.0'              # Constraint Programmatically.
  
  pod 'RxSwift',                    '~> 4.5.0'              # Reactive/Functional Programming Framework#
  pod 'RxCocoa',                    '~> 4.5.0'              # Reactive/Functional Programming Framework
  
  target 'LemiTravelTests' do
    test_pods
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
